version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies at repo root..."
      - if [ -f package-lock.json ]; then npm ci; else npm install; fi

  build:
    commands:
      - echo "Build started on date"
      - if npm run | grep -q "build"; then npm run build; else echo "No build script"; fi

artifacts:
  files:
    - '/*'
  discard-paths: no
